#
# CISE sim application configuration (@project.version@)
#

# The server section allows to modify the port used by the CISE Sim.
# To receive CISE messages and to serve the UI of the CISE Sim application
# The admin port is used to gather statistics of the communication
server:
  applicationConnectors:
    - type: http
      port: 8200
  adminConnectors:
    - type: http
      port: 8201

# The logging section is used to tweak the logging level of the simulator.
# To write the log in a file instead of the standard output is possible to
# uncomment the "type file" section.
logging:
  level: INFO
  loggers:
    "io.dropwizard.bundles.assets": INFO
    "eu.cise.dispatcher": DEBUG
    "org.apache.cxf": WARN
    "eu.cise.emulator.api": DEBUG
    "org.eclipse.jetty.server.handler": WARN
    "org.eclipse.jetty.setuid": WARN
    "io.dropwizard.server.DefaultServerFactory": WARN
    "io.dropwizard.bundles.assets.ConfiguredAssetsBundle": WARN
    "org.wiremock": INFO
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
      logFormat: "%highlight(%.-1level)|%message%n"
    - type: file
      threshold: ALL
      logFormat: "%d{HH:mm:ss}[%5.-5thread]%-5.5level|%-25.25logger{1}|%msg%n"
      currentLogFilename: ./logs/sim.log
      archivedLogFilenamePattern: ./logs/sim-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 5
      timeZone: UTC
